micronaut:
  application:
    name: projetoKeyManagerPixGRPC
datasources:
  default:
    url: ${DB_URL:`jdbc:mysql://localhost:3306/pix?createDatabaseIfNotExist=true&serverTimezone=UTC`}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}
    dialect: "org.hibernate.dialect.MySQL5InnoDBDialect"
jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true

grpc:
  server:
    port: ${SERVER_PORT:50051}

logger:
  levels:
    io.micronaut.transaction: DEBUG

url:
  itau:
    erp: ${URL.ERP.ITAU:`http://localhost:9091`}